INSERT INTO PROVINCES(PROVINCEDESC) VALUES ('Lima');
INSERT INTO PROVINCES(PROVINCEDESC) VALUES ('Cajamarca');
INSERT INTO PROVINCES(PROVINCEDESC) VALUES ('San Martin');

INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Puente Piedra', 1);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Los Olivos', 1);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('San Isidro', 1);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Miraflores', 1);

INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Cajamarca', 2);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Encañada', 2);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('San Juan', 2);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Chetilla', 2);

INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('El Porvenir', 3);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('San Antonio', 3);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Tarapoto', 3);
INSERT INTO DISTRICTS(DISTRICTDESC, IDPROVINCE) VALUES ('Juan Guerra', 3);

INSERT INTO LOCATIONS(LOCATIONDESC) VALUES ('Sede Puente Piedra');
INSERT INTO LOCATIONS(LOCATIONDESC) VALUES ('Sede San Isidro');
INSERT INTO LOCATIONS(LOCATIONDESC) VALUES ('Sede Cajamarca');
INSERT INTO LOCATIONS(LOCATIONDESC) VALUES ('Sede San Antonio');

INSERT INTO MANAGERS(MANAGERDESC) VALUES ('Felipe Soza Gutierres');
INSERT INTO MANAGERS(MANAGERDESC) VALUES ('Raul Mendoza Chavez');
INSERT INTO MANAGERS(MANAGERDESC) VALUES ('Luis Chacon Zarate');
INSERT INTO MANAGERS(MANAGERDESC) VALUES ('Manolo Guerra Manrrique');

INSERT INTO CONDITIONS(CONDITIONDESC) VALUES ('Habilitado');
INSERT INTO CONDITIONS(CONDITIONDESC) VALUES ('En mantenimiento');
INSERT INTO CONDITIONS(CONDITIONDESC) VALUES ('Deshabilitado');

INSERT INTO HOSPITALS(HOSPITALNAME, HOSPITALAGE, HOSPITALAREA, IDMANAGER, IDCONDITION, IDLOCATION, IDDISTRICT) 
VALUES ('Hospital Sr. de Luren', 10, 300.50, 1, 1, 1, 3);
INSERT INTO HOSPITALS(HOSPITALNAME, HOSPITALAGE, HOSPITALAREA, IDMANAGER, IDCONDITION, IDLOCATION, IDDISTRICT) 
VALUES ('Hospital Montenor', 8, 200.00, 2, 2, 2, 1);
INSERT INTO HOSPITALS(HOSPITALNAME, HOSPITALAGE, HOSPITALAREA, IDMANAGER, IDCONDITION, IDLOCATION, IDDISTRICT) 
VALUES ('Hospital Dr Quito', 20, 180.90, 3, 2, 3, 6);
INSERT INTO HOSPITALS(HOSPITALNAME, HOSPITALAGE, HOSPITALAREA, IDMANAGER, IDCONDITION, IDLOCATION, IDDISTRICT) 
VALUES ('Hospital Constantino', 2, 250.50, 4, 1, 4, 10);

SELECT * FROM HOSPITALS;