-- CONDITION
CREATE SEQUENCE CONDITIONS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER CONDITIONS_TRG
BEFORE INSERT ON CONDITIONS
FOR EACH ROW
BEGIN
  SELECT CONDITIONS_ID_SEQ.NEXTVAL INTO :NEW.IDCONDITION FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- DISTRICT
CREATE SEQUENCE DISTRICTS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER DISTRICTS_TRG
BEFORE INSERT ON DISTRICTS
FOR EACH ROW
BEGIN
  SELECT DISTRICTS_ID_SEQ.NEXTVAL INTO :NEW.IDDISTRICT FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- HOSPITAL
CREATE SEQUENCE HOSPITALS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER HOSPITALS_TRG
BEFORE INSERT ON HOSPITALS
FOR EACH ROW
BEGIN
  SELECT HOSPITALS_ID_SEQ.NEXTVAL INTO :NEW.IDHOSPITAL FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- LOCATION
CREATE SEQUENCE LOCATIONS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER LOCATIONS_TRG
BEFORE INSERT ON LOCATIONS
FOR EACH ROW
BEGIN
  SELECT LOCATIONS_ID_SEQ.NEXTVAL INTO :NEW.IDLOCATION FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- MANAGER
CREATE SEQUENCE MANAGERS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER MANAGERS_TRG
BEFORE INSERT ON MANAGERS
FOR EACH ROW
BEGIN
  SELECT MANAGERS_ID_SEQ.NEXTVAL INTO :NEW.IDMANAGER FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- PROVINCE
CREATE SEQUENCE PROVINCES_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER PROVINCES_TRG
BEFORE INSERT ON PROVINCES
FOR EACH ROW
BEGIN
  SELECT PROVINCES_ID_SEQ.NEXTVAL INTO :NEW.IDPROVINCE FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;

-- USERS
CREATE SEQUENCE USERS_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER USERS_TRG
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  SELECT USERS_ID_SEQ.NEXTVAL INTO :NEW.IDUSER FROM DUAL;
  :NEW.CREATEDAT := SYSDATE;
END;
